CREATE TABLE Users (
	ID INT IDENTITY(1, 1) NOT NULL,
	Identifier NVARCHAR(100) NOT NULL,
	EMail NVARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
)
GO

CREATE TABLE Seasons (
	ID INT IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	PRIMARY KEY(ID)
)

CREATE TABLE UserTeams (
	ID INT IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(100) NOT NULL,
	UserID INT NOT NULL,
	SeasonId INT NOT NULL,
	PRIMARY KEY (ID),
	CONSTRAINT FK_UserTeams_UserID FOREIGN KEY (UserID) REFERENCES Users(ID) ON DELETE CASCADE,
	CONSTRAINT FK_UserTeams_SeasonID  FOREIGN KEY (SeasonID) REFERENCES Seasons(ID) ON DELETE CASCADE
)
GO