CREATE TABLE Users (
	Id INT IDENTITY(1, 1) NOT NULL,
	Identifier NVARCHAR(100) NOT NULL,
	EMail NVARCHAR(100) NOT NULL,
	PRIMARY KEY (Id)
)
GO

CREATE TABLE Seasons (
	Id INT IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	PRIMARY KEY(Id)
)

CREATE TABLE UserTeams (
	Id INT IDENTITY(1, 1) NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	UserId INT NOT NULL,
	SeasonId INT NOT NULL,
	PRIMARY KEY (Id),
	CONSTRAINT FK_UserTeams_UserId FOREIGN KEY (UserId) REFERENCES Users(Id) ON DELETE CASCADE,
	CONSTRAINT FK_UserTeams_SeasonId  FOREIGN KEY (SeasonId) REFERENCES Seasons(Id) ON DELETE CASCADE
)
GO