CREATE TABLE Players (
	Id INT IDENTITY NOT NULL,
	FirstName NVARCHAR(50) NOT NULL,
	LastName NVARCHAR(50) NOT NULL,
	BirthDate NVARCHAR(20) NOT NULL,
	BirthCountry NVARCHAR(50) NOT NULL,
	BirthPlace NVARCHAR(50) NOT NULL,
	Nationality NVARCHAR(50) NOT NULL,
	Height NVARCHAR(10) NOT NULL,
	Weight NVARCHAR(10) NOT NULL,
	Position NVARCHAR(50) NOT NULL,
	Photo NVARCHAR(100) NOT NULL,
	Active BIT NOT NULL,
	PRIMARY KEY (Id)
)
GO

CREATE TABLE UserTeamSquads (
	Id INT IDENTITY (1, 1) NOT NULL,
	UserTeamId INT NOT NULL,
	PlayerId INT NOT NULL,
	PRIMARY KEY (Id),
	CONSTRAINT FK_UserTeamSquads_UserTeamId FOREIGN KEY (UserTeamId) REFERENCES UserTeams(Id) ON DELETE CASCADE,
	CONSTRAINT FK_UserTeamSquads_PlayerId FOREIGN KEY (PlayerId) REFERENCES Players(Id) ON DELETE CASCADE
)
GO