CREATE TABLE Leagues (
	Id INT NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Country NVARCHAR(25) NOT NULL,
	Logo NVARCHAR(100) NOT NULL,
	Flag NVARCHAR(100) NOT NULL,
	PRIMARY KEY (Id),
);
GO

CREATE TABLE Teams (
	Id INT NOT NULL,
	Name NVARCHAR(50) NOT NULL,
	Logo NVARCHAR(100) NOT NULL,
	LeagueId INT NOT NULL
	PRIMARY KEY (Id),
	CONSTRAINT FK_Teams_LeagueId FOREIGN KEY (LeagueId) REFERENCES Leagues(Id) ON DELETE CASCADE,
);